name: algorand_dart
description: Unofficial community SDK to interact with the Algorand network, for Dart & Flutter
version: 0.0.1-dev.1
homepage: https://www.algorand.com

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  # Ed25519 - nullsafety
  cryptography: ^2.0.0-nullsafety.2 #- waiting for retrofit generator

  # SHA512/256 - nullsafety
  crypto: ^3.0.0

  # Base32 - nullsafety
  base32: ^2.0.0-nullsafety.1

  # Convert - nullsafety
  convert: ^3.0.0

  # Easily work with bytes - nullsafety
  buffer: ^1.1.0-nullsafety.0

  # Sanitization - nullsafety
  string_validator: ^0.2.0-nullsafety.0

  # Equatable - nullsafety
  equatable: ^2.0.0

  # JSON Annotation
  json_annotation: ^4.0.0

  # Equality - nullsafety
  collection: ^1.15.0

  # HTTP & REST (Update to v4 when stable)
  dio: ^3.0.10
  #retrofit: ^1.3.4+1

  # Messagepack
  msgpack_dart: ^0.0.7

dev_dependencies:
  # Testing framework
  test: ^1.16.5

  # Build Runner & Source Generation
  build_runner: ^1.11.5

  # HTTP REST
  #retrofit_generator: ^1.4.1+3
